/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nazhiif Yahya
 */
public class aplikasiParkir extends javax.swing.JFrame {

    /**
     * Creates new form aplikasiParkir
     */
    int noParkirMotor;
    int noParkirMobil;
    int indexKendaraan;
    
    public aplikasiParkir() {
        initComponents();
        noParkirMotor = 0;
        noParkirMobil = 0;
        indexKendaraan = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKendaraanMasukButtonGroup = new javax.swing.ButtonGroup();
        jenisKendaraanKeluarButtonGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        navigasiHomeLabel = new javax.swing.JLabel();
        pesanHomeLabel = new javax.swing.JLabel();
        parkirMasukPanel = new javax.swing.JPanel();
        navigasiParkirMasukLabel = new javax.swing.JLabel();
        jenisKendaraanMasukLabel = new javax.swing.JLabel();
        motorMasukRadioButton = new javax.swing.JRadioButton();
        mobilMasukRadioButton = new javax.swing.JRadioButton();
        platNomorMasukLabel = new javax.swing.JLabel();
        platNomorMasukTextField = new javax.swing.JTextField();
        submitMasukButton = new javax.swing.JButton();
        resetMasukButton = new javax.swing.JButton();
        noParkirMasukLabel = new javax.swing.JLabel();
        noParkirMasukTextField = new javax.swing.JTextField();
        parkirMasukScrollPane = new javax.swing.JScrollPane();
        parkirMasukTextArea = new javax.swing.JTextArea();
        parkirKeluarPanel = new javax.swing.JPanel();
        navigasiParkirKeluarLabel = new javax.swing.JLabel();
        noParkirKeluarLabel = new javax.swing.JLabel();
        noParkirKeluarTextField = new javax.swing.JTextField();
        cariNoParkirKeluarButton = new javax.swing.JButton();
        resetNoParkirKeluarButton = new javax.swing.JButton();
        jenisKendaraanKeluarLabel = new javax.swing.JLabel();
        motorKeluarRadioButton = new javax.swing.JRadioButton();
        mobilKeluarRadioButton = new javax.swing.JRadioButton();
        platNomorKeluarLabel = new javax.swing.JLabel();
        platNomorKeluarTextField = new javax.swing.JTextField();
        lamaParkirLabel = new javax.swing.JLabel();
        lamaParkirTextField = new javax.swing.JTextField();
        biayaLabel = new javax.swing.JLabel();
        biayaTextField = new javax.swing.JTextField();
        parkirKeluarScrollPane = new javax.swing.JScrollPane();
        parkirKeluarTextArea = new javax.swing.JTextArea();
        submitKeluarButton = new javax.swing.JButton();
        resetKeluarButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        homeMenuItem = new javax.swing.JMenuItem();
        tutupMenuItem = new javax.swing.JMenuItem();
        parkirMenu = new javax.swing.JMenu();
        parkirMasukMenuItem = new javax.swing.JMenuItem();
        parkirKeluarMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        navigasiHomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        navigasiHomeLabel.setText("File >> Home");

        pesanHomeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pesanHomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pesanHomeLabel.setText("Selamat Datang!");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(navigasiHomeLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pesanHomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigasiHomeLabel)
                .addGap(131, 131, 131)
                .addComponent(pesanHomeLabel)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        mainPanel.add(homePanel, "card2");

        navigasiParkirMasukLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        navigasiParkirMasukLabel.setText("Parkir >> Parkir Masuk");

        jenisKendaraanMasukLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jenisKendaraanMasukLabel.setText("Jenis Kendaraan");

        jenisKendaraanMasukButtonGroup.add(motorMasukRadioButton);
        motorMasukRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        motorMasukRadioButton.setText("Motor");
        motorMasukRadioButton.setActionCommand("Motor");

        jenisKendaraanMasukButtonGroup.add(mobilMasukRadioButton);
        mobilMasukRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mobilMasukRadioButton.setText("Mobil");
        mobilMasukRadioButton.setActionCommand("Mobil");

        platNomorMasukLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        platNomorMasukLabel.setText("Plat Nomor");

        submitMasukButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitMasukButton.setText("Submit");
        submitMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitMasukButtonActionPerformed(evt);
            }
        });

        resetMasukButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetMasukButton.setText("Reset");
        resetMasukButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMasukButtonActionPerformed(evt);
            }
        });

        noParkirMasukLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noParkirMasukLabel.setText("No Parkir");

        noParkirMasukTextField.setEditable(false);
        noParkirMasukTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noParkirMasukTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        parkirMasukTextArea.setEditable(false);
        parkirMasukTextArea.setColumns(20);
        parkirMasukTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        parkirMasukTextArea.setRows(5);
        parkirMasukTextArea.setText("No. Parkir | Jenis Kendaraan | Plat Nomor");
        parkirMasukScrollPane.setViewportView(parkirMasukTextArea);

        javax.swing.GroupLayout parkirMasukPanelLayout = new javax.swing.GroupLayout(parkirMasukPanel);
        parkirMasukPanel.setLayout(parkirMasukPanelLayout);
        parkirMasukPanelLayout.setHorizontalGroup(
            parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parkirMasukScrollPane)
                    .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                        .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                                .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenisKendaraanMasukLabel)
                                    .addComponent(platNomorMasukLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                                        .addComponent(motorMasukRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mobilMasukRadioButton))
                                    .addComponent(platNomorMasukTextField)))
                            .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                                .addComponent(submitMasukButton)
                                .addGap(18, 18, 18)
                                .addComponent(resetMasukButton)))
                        .addGap(71, 71, 71)
                        .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noParkirMasukLabel)
                            .addComponent(noParkirMasukTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                    .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                        .addComponent(navigasiParkirMasukLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        parkirMasukPanelLayout.setVerticalGroup(
            parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navigasiParkirMasukLabel)
                .addGap(18, 18, 18)
                .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKendaraanMasukLabel)
                    .addComponent(motorMasukRadioButton)
                    .addComponent(mobilMasukRadioButton)
                    .addComponent(noParkirMasukLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(parkirMasukPanelLayout.createSequentialGroup()
                        .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(platNomorMasukLabel)
                            .addComponent(platNomorMasukTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parkirMasukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitMasukButton)
                            .addComponent(resetMasukButton)))
                    .addComponent(noParkirMasukTextField))
                .addGap(18, 18, 18)
                .addComponent(parkirMasukScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(parkirMasukPanel, "card3");

        navigasiParkirKeluarLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        navigasiParkirKeluarLabel.setText("Parkir >> Parkir Keluar");

        noParkirKeluarLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noParkirKeluarLabel.setText("No Parkir");

        noParkirKeluarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cariNoParkirKeluarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cariNoParkirKeluarButton.setText("Cari");
        cariNoParkirKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariNoParkirKeluarButtonActionPerformed(evt);
            }
        });

        resetNoParkirKeluarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetNoParkirKeluarButton.setText("Reset");
        resetNoParkirKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetNoParkirKeluarButtonActionPerformed(evt);
            }
        });

        jenisKendaraanKeluarLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jenisKendaraanKeluarLabel.setText("Jenis Kendaraan");

        jenisKendaraanKeluarButtonGroup.add(motorKeluarRadioButton);
        motorKeluarRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        motorKeluarRadioButton.setText("Motor");
        motorKeluarRadioButton.setActionCommand("Motor");
        motorKeluarRadioButton.setEnabled(false);

        jenisKendaraanKeluarButtonGroup.add(mobilKeluarRadioButton);
        mobilKeluarRadioButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mobilKeluarRadioButton.setText("Mobil");
        mobilKeluarRadioButton.setActionCommand("Mobil");
        mobilKeluarRadioButton.setEnabled(false);

        platNomorKeluarLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        platNomorKeluarLabel.setText("Plat Nomor");

        platNomorKeluarTextField.setEditable(false);
        platNomorKeluarTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lamaParkirLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lamaParkirLabel.setText("Lama Parkir");

        lamaParkirTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        biayaLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        biayaLabel.setText("Biaya");

        biayaTextField.setEditable(false);
        biayaTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        parkirKeluarTextArea.setEditable(false);
        parkirKeluarTextArea.setColumns(20);
        parkirKeluarTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        parkirKeluarTextArea.setRows(5);
        parkirKeluarTextArea.setText("No. Parkir | Jenis Kendaraan | Plat Nomor | Lama Parkir | Biaya");
        parkirKeluarScrollPane.setViewportView(parkirKeluarTextArea);

        submitKeluarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitKeluarButton.setText("Submit");
        submitKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitKeluarButtonActionPerformed(evt);
            }
        });

        resetKeluarButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetKeluarButton.setText("Reset");
        resetKeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetKeluarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parkirKeluarPanelLayout = new javax.swing.GroupLayout(parkirKeluarPanel);
        parkirKeluarPanel.setLayout(parkirKeluarPanelLayout);
        parkirKeluarPanelLayout.setHorizontalGroup(
            parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parkirKeluarScrollPane)
                    .addComponent(navigasiParkirKeluarLabel)
                    .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                        .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                                .addComponent(noParkirKeluarLabel)
                                .addGap(40, 40, 40)
                                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                                        .addComponent(cariNoParkirKeluarButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(resetNoParkirKeluarButton))
                                    .addComponent(noParkirKeluarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenisKendaraanKeluarLabel)
                                    .addComponent(platNomorKeluarLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                                        .addComponent(motorKeluarRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mobilKeluarRadioButton))
                                    .addComponent(platNomorKeluarTextField))))
                        .addGap(53, 53, 53)
                        .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(biayaLabel)
                            .addComponent(biayaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                                .addComponent(lamaParkirLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lamaParkirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                                .addComponent(submitKeluarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetKeluarButton)))))
                .addContainerGap())
        );
        parkirKeluarPanelLayout.setVerticalGroup(
            parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                        .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(noParkirKeluarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parkirKeluarPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lamaParkirLabel)
                                    .addComponent(lamaParkirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cariNoParkirKeluarButton)
                            .addComponent(resetNoParkirKeluarButton)
                            .addComponent(submitKeluarButton)
                            .addComponent(resetKeluarButton)))
                    .addGroup(parkirKeluarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(navigasiParkirKeluarLabel)
                        .addGap(18, 18, 18)
                        .addComponent(noParkirKeluarLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenisKendaraanKeluarLabel)
                    .addComponent(motorKeluarRadioButton)
                    .addComponent(mobilKeluarRadioButton)
                    .addComponent(biayaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(parkirKeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platNomorKeluarLabel)
                    .addComponent(platNomorKeluarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biayaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(parkirKeluarScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(parkirKeluarPanel, "card4");

        fileMenu.setText("File");

        homeMenuItem.setText("Home");
        homeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(homeMenuItem);

        tutupMenuItem.setText("Tutup");
        tutupMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutupMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(tutupMenuItem);

        jMenuBar1.add(fileMenu);

        parkirMenu.setText("Parkir");

        parkirMasukMenuItem.setText("Parkir Masuk");
        parkirMasukMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkirMasukMenuItemActionPerformed(evt);
            }
        });
        parkirMenu.add(parkirMasukMenuItem);

        parkirKeluarMenuItem.setText("Parkir Keluar");
        parkirKeluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkirKeluarMenuItemActionPerformed(evt);
            }
        });
        parkirMenu.add(parkirKeluarMenuItem);

        jMenuBar1.add(parkirMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuItemActionPerformed
        // TODO add your handling code here:
        homePanel.setVisible(true);
        parkirMasukPanel.setVisible(false);
        parkirKeluarPanel.setVisible(false);
    }//GEN-LAST:event_homeMenuItemActionPerformed

    private void tutupMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutupMenuItemActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_tutupMenuItemActionPerformed

    private void parkirMasukMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkirMasukMenuItemActionPerformed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        parkirMasukPanel.setVisible(true);
        parkirKeluarPanel.setVisible(false);
    }//GEN-LAST:event_parkirMasukMenuItemActionPerformed

    private void parkirKeluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkirKeluarMenuItemActionPerformed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        parkirMasukPanel.setVisible(false);
        parkirKeluarPanel.setVisible(true);
    }//GEN-LAST:event_parkirKeluarMenuItemActionPerformed

    private void submitMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitMasukButtonActionPerformed
        // TODO add your handling code here:
        if(jenisKendaraanMasukButtonGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(this, "Silakan Pilih Jenis Kendaraan!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(platNomorMasukTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silakan Masukkan Plat Nomor!", "Error", JOptionPane.ERROR_MESSAGE);
        } else{
            if(jenisKendaraanMasukButtonGroup.getSelection().getActionCommand().equals("Motor")) {
                noParkirMasukTextField.setText("P-MTR-" + String.format("%04d", noParkirMotor));
                noParkirMotor++;
                
                kendaraan.add(new String[]{noParkirMasukTextField.getText(), 
                jenisKendaraanMasukButtonGroup.getSelection().getActionCommand(), 
                platNomorMasukTextField.getText()});
        
                parkirMasukTextArea.append("\n" + kendaraan.get(indexKendaraan)[0] + " | " +
                    kendaraan.get(indexKendaraan)[1] + " | " +
                    kendaraan.get(indexKendaraan)[2]);
                indexKendaraan++;
            } else if(jenisKendaraanMasukButtonGroup.getSelection().getActionCommand().equals("Mobil")) {            
                noParkirMasukTextField.setText("P-MBL-" + String.format("%04d", noParkirMobil));
                noParkirMobil++;
                
                kendaraan.add(new String[]{noParkirMasukTextField.getText(), 
                jenisKendaraanMasukButtonGroup.getSelection().getActionCommand(), 
                platNomorMasukTextField.getText()});
        
                parkirMasukTextArea.append("\n" + kendaraan.get(indexKendaraan)[0] + " | " +
                    kendaraan.get(indexKendaraan)[1] + " | " +
                    kendaraan.get(indexKendaraan)[2]);
                indexKendaraan++;
            }
        }
    }//GEN-LAST:event_submitMasukButtonActionPerformed

    private void resetMasukButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMasukButtonActionPerformed
        // TODO add your handling code here:
        jenisKendaraanMasukButtonGroup.clearSelection();
        platNomorMasukTextField.setText("");
        noParkirMasukTextField.setText("");
    }//GEN-LAST:event_resetMasukButtonActionPerformed

    private void cariNoParkirKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariNoParkirKeluarButtonActionPerformed
        // TODO add your handling code here:
        if(noParkirKeluarTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silakan Masukkan No Parkir!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean ketemu = false;
            for(String[] i: kendaraan) {
                if(i[0].equals(noParkirKeluarTextField.getText())) {
                    if(i[1].equals("Motor")) {
                        jenisKendaraanKeluarButtonGroup.setSelected(motorKeluarRadioButton.getModel(), true);
                        platNomorKeluarTextField.setText(i[2]);
                        ketemu = true;
                        break;
                    } else if(i[1].equals("Mobil")) {
                        jenisKendaraanKeluarButtonGroup.setSelected(mobilKeluarRadioButton.getModel(), true);
                        platNomorKeluarTextField.setText(i[2]);
                        ketemu = true;
                        break;
                    }
                }
            }
            if(ketemu == false) {
                JOptionPane.showMessageDialog(this, "Data Tidak Ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cariNoParkirKeluarButtonActionPerformed

    private void resetNoParkirKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetNoParkirKeluarButtonActionPerformed
        // TODO add your handling code here:
        noParkirKeluarTextField.setText("");
        jenisKendaraanKeluarButtonGroup.clearSelection();
        platNomorKeluarTextField.setText("");
        
    }//GEN-LAST:event_resetNoParkirKeluarButtonActionPerformed

    private void submitKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitKeluarButtonActionPerformed
        // TODO add your handling code here:
        if(noParkirKeluarTextField.getText().equals("") || 
                jenisKendaraanKeluarButtonGroup.getSelection() == null ||
                platNomorKeluarTextField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data Belum Lengkap", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(lamaParkirTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silakan Masukkan Lama Parkir!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            float biaya;
            float lamaParkir = Float.valueOf(lamaParkirTextField.getText());
            if(jenisKendaraanKeluarButtonGroup.getSelection().getActionCommand().equals("Motor")) {
                biaya = 2000*lamaParkir;
                biayaTextField.setText(String.format("Rp%.02f", biaya));
            } else if(jenisKendaraanKeluarButtonGroup.getSelection().getActionCommand().equals("Mobil")) {
                biaya = 5000*lamaParkir;
                biayaTextField.setText(String.format("Rp%.02f", biaya));
            }
            parkirKeluarTextArea.append("\n" + noParkirKeluarTextField.getText() + " | " +
                    jenisKendaraanKeluarButtonGroup.getSelection().getActionCommand() + " | " +
                    platNomorKeluarTextField.getText() + " | " +
                    lamaParkirTextField.getText() +  " Jam | " +
                    biayaTextField.getText());
        }
    }//GEN-LAST:event_submitKeluarButtonActionPerformed

    private void resetKeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetKeluarButtonActionPerformed
        // TODO add your handling code here:
        noParkirKeluarTextField.setText("");
        jenisKendaraanKeluarButtonGroup.clearSelection();
        platNomorKeluarTextField.setText("");
        lamaParkirTextField.setText("");
        biayaTextField.setText("");
    }//GEN-LAST:event_resetKeluarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasiParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel biayaLabel;
    private javax.swing.JTextField biayaTextField;
    private javax.swing.JButton cariNoParkirKeluarButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem homeMenuItem;
    private javax.swing.JPanel homePanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.ButtonGroup jenisKendaraanKeluarButtonGroup;
    private javax.swing.JLabel jenisKendaraanKeluarLabel;
    private javax.swing.ButtonGroup jenisKendaraanMasukButtonGroup;
    private javax.swing.JLabel jenisKendaraanMasukLabel;
    private javax.swing.JLabel lamaParkirLabel;
    private javax.swing.JTextField lamaParkirTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton mobilKeluarRadioButton;
    private javax.swing.JRadioButton mobilMasukRadioButton;
    private javax.swing.JRadioButton motorKeluarRadioButton;
    private javax.swing.JRadioButton motorMasukRadioButton;
    private javax.swing.JLabel navigasiHomeLabel;
    private javax.swing.JLabel navigasiParkirKeluarLabel;
    private javax.swing.JLabel navigasiParkirMasukLabel;
    private javax.swing.JLabel noParkirKeluarLabel;
    private javax.swing.JTextField noParkirKeluarTextField;
    private javax.swing.JLabel noParkirMasukLabel;
    private javax.swing.JTextField noParkirMasukTextField;
    private javax.swing.JMenuItem parkirKeluarMenuItem;
    private javax.swing.JPanel parkirKeluarPanel;
    private javax.swing.JScrollPane parkirKeluarScrollPane;
    private javax.swing.JTextArea parkirKeluarTextArea;
    private javax.swing.JMenuItem parkirMasukMenuItem;
    private javax.swing.JPanel parkirMasukPanel;
    private javax.swing.JScrollPane parkirMasukScrollPane;
    private javax.swing.JTextArea parkirMasukTextArea;
    private javax.swing.JMenu parkirMenu;
    private javax.swing.JLabel pesanHomeLabel;
    private javax.swing.JLabel platNomorKeluarLabel;
    private javax.swing.JTextField platNomorKeluarTextField;
    private javax.swing.JLabel platNomorMasukLabel;
    private javax.swing.JTextField platNomorMasukTextField;
    private javax.swing.JButton resetKeluarButton;
    private javax.swing.JButton resetMasukButton;
    private javax.swing.JButton resetNoParkirKeluarButton;
    private javax.swing.JButton submitKeluarButton;
    private javax.swing.JButton submitMasukButton;
    private javax.swing.JMenuItem tutupMenuItem;
    // End of variables declaration//GEN-END:variables

    ArrayList<String[]> kendaraan = new ArrayList<>();
}
